DROP DATABASE IF EXISTS cms;
CREATE DATABASE cms;

USE cms;

CREATE TABLE admin(
  aid INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(12) NOT NULL,
  password VARCHAR(128) NOT NULL,
  profile_pic VARCHAR(128) NOT NULL,
  PRIMARY KEY(aid)
);

CREATE TABLE content(
  cid INT NOT NULL AUTO_INCREMENT,
  aid INT NOT NULL,
  title VARCHAR(42) NOT NULL,
  content LONGTEXT NOT NULL,
  entry_date DATE NOT NULL,
  edited TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL,
  PRIMARY KEY(cid),
  FOREIGN KEY(aid) REFERENCES admin(aid)
  ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE visitors (
  vid INT NOT NULL AUTO_INCREMENT,
  ip VARCHAR(12) NOT NULL,
  visited TIMESTAMP NOT NULL,
  PRIMARY KEY(vid)
);

CREATE USER 'content'@'localhost' IDENTIFIED BY '1337';
GRANT ALL ON cms.* TO 'content'@'localhost';
